blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('kategori/<int:kategori>',views.bykategori,name='kategori'),
    path('<slug:blogslug>',views.show,name='show'),
    path('',views.index,name='index'),
]

lancarjaya/urls.py
from django.contrib import admin
from django.conf import settings	
from django.urls import path , include
from django.conf.urls.static import static
from . import views
admin.site.site_header = "Lancar Jaya Shop"
admin.site.site_title = "LJS"
admin.site.index_title = "Lancar Jaya Shop Admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('produk/',include('produk.urls')),
    path('galeri/',include('galeri.urls')),
    path('testimoni/',include('testimoni.urls')),
    path('kontak/',include('contact.urls')),
    path('cara_belanja/',views.cara_belanja,name='cara_belanja'),
    path('cara_verifikasi/',views.cara_verifikasi,name='cara_verifikasi'),
    path('user/',include('users.urls')),
    path('pencarian/',views.pencarian,name='pencarian'),
    path('keranjang/',include('transaksi.urls')),
    path('',views.index,name='index'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produk/urls.py
from django.urls import path
from . import views
app_name = 'produk'

urlpatterns=[
    path('',views.index,name='index'),
    path('<slug:slugbarang>',views.show,name='show'),
    path('kategori/<slug:slugkategori>',views.kategori,name='kategori')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name='users'

urlpatterns = [
    path('register',views.register,name='register'),
    path('editprofile',views.editprofile,name='editprofile'),
    path('alamat',views.tambahalamat,name='tambah-alamat'),
    path('alamat/edit',views.editalamat,name='edit-alamat'),
    path('login',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]

produk/models.py
from django.db import models
from django.utils.text import slugify

class kategori(models.Model):
    nama = models.CharField(max_length=50,unique=True)
    tanggal_buat = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True,editable=False)
    
    def save(self):
      self.slug=slugify(self.nama)
      super(kategori, self).save()

    def __str__(self):
        return self.nama

class barang(models.Model):
    nama = models.CharField(max_length=50,unique=True)
    deskripsi = models.TextField()
    harga = models.IntegerField()
    diskon = models.IntegerField()
    berat = models.IntegerField(default=0)
    stok = models.IntegerField()
    tanggal_buat = models.DateTimeField(auto_now_add=True)
    kategori = models.ForeignKey(kategori,on_delete=models.SET_NULL,null=True)
    slug = models.SlugField(null=True,editable=False)
    gambar = models.ImageField(upload_to='produk/',null=True,blank=True)
    status_aktiv = models.BooleanField(default=False)

    def save(self):
      self.slug=slugify(self.nama)
      super(barang, self).save()

    def __str__(self):
        return self.nama

produk/forms.py
from django import forms

class form_keranjang(forms.Form):
    jumlah = forms.IntegerField(
        label=False,
        widget=forms.TextInput(
            attrs={
                'id':'jumlah',
                'type':'number',
                'min':'0',
                'class':'input-md form-control',
                'placeholder':'Jumlah',
            }
        ))

produk/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from . import models
from contact import models as contactmodel
from django.core.paginator import Paginator
from transaksi.models import keranjang
from . import forms

def index(request):
    data_produk = models.barang.objects.all().filter(status_aktiv=1).order_by('-id')
    paginator = Paginator(data_produk, 9)
    page = request.GET.get('page')
    data_produk = paginator.get_page(page)
    data_kategori = models.kategori.objects.order_by('-id').all()
    context = {
        'produk':data_produk,
        'kategori':data_kategori,
    }
    return render(request,'produk/index.html',context)

def show(request,slugbarang):
    hargabarangnya = 0
    if request.method == 'POST':
        jumlahnya = keranjang.objects.filter(barang=models.barang.objects.get(id=request.POST['barang']),kode_transaksi__isnull=True,pembeli=User.objects.get(id=request.POST['user'])).count()
        dbarang = models.barang.objects.get(id=request.POST['barang'])
        if dbarang.diskon > 0:
            jumlahdiskon = int(dbarang.harga)*int(dbarang.diskon)/100
            hargabarangnya = (int(dbarang.harga)-int(jumlahdiskon))*int(request.POST['jumlah'])
        else:
            hargabarangnya = int(dbarang.harga)*int(request.POST['jumlah'])

        beratbarang = int(dbarang.berat)*int(request.POST['jumlah'])
        if jumlahnya > 0 :
            t = keranjang.objects.get(kode_transaksi__isnull=True,barang=models.barang.objects.get(id=request.POST['barang']), pembeli=User.objects.get(id=request.POST['user']))
            t.jumlah = int(t.jumlah) + int(request.POST['jumlah']) 
            t.total = int(t.total)+int(hargabarangnya)
            t.berat_total = int(t.berat_total) + int(beratbarang)
            t.save()
        else:
            keranjang.objects.create(
            jumlah=request.POST['jumlah'],
            barang = models.barang.objects.get(id=request.POST['barang']),
            pembeli = User.objects.get(id=request.POST['user']),
            berat_total = int(beratbarang),
            total= int(hargabarangnya),
            )
        
        messages.success(request,'Berhasil menambah ke keranjang belanja')
        return redirect('produk:show',slugbarang=slugbarang)

    data_kontak = contactmodel.contact.objects.all().order_by('-id')[0:1]
    data_barang = models.barang.objects.get(slug=slugbarang)
    context = {
        'barang':data_barang,
        'contact':data_kontak,
        'form':forms.form_keranjang,
    }
    return render(request,'produk/show.html',context)

def kategori(request,slugkategori):
    data_kategori = models.kategori.objects.get(slug=slugkategori)
    data_barang = models.barang.objects.filter(status_aktiv=1).filter(kategori=data_kategori.id).order_by('-id')
    data_list_kategori = models.kategori.objects.order_by('-id').all()
    context = {
        'produk':data_barang,
        'detailkategori':data_kategori,
        'kategori':data_list_kategori,
    }
    return render(request,'produk/kategori.html',context)

produk/templates/produk/index.html
{% extends 'layout/base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">

        <div class="row">

            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Produk</h1>
                <div class="hs-line-4 font-alt">
                    Pilih produk terbaik di toko kami
                </div>
            </div>
        </div>

    </div>
</section>
<section class="page-section">
    <div class="container relative">

        <div class="row">
            <div class="col-sm-8">

                <div class="row multi-columns-row">
                    {% for row in produk %}
                    <div class="col-md-4 col-lg-4 mb-60 mb-xs-40">

                        <div class="post-prev-img">
                            {% if row.gambar %}
                            <img src="{{row.gambar.url}}" alt="" />
                            {% endif %}

                            {% if row.stok != 0 %}
                            {% if row.diskon != 0 %}
                            <div class="intro-label">
                                <span class="label label-danger bg-green">{{row.diskon}}%</span>
                            </div>
                            {% endif%}
                            {% else %}
                            <div class="intro-label">
                                <span class="label label-danger bg-red">Habis</span>
                            </div>
                            {% endif %}
                        </div>
                        <div class="post-prev-title font-alt align-center">
                            <a href="{% url 'produk:show' row.slug %}">{{row.nama}}</a>
                        </div>

                        <div class="post-prev-text align-center">
                            Stok : {{row.stok}} Pcs <br>
                            {% if row.diskon != 0 %}
                            <del>Rp. {{row.harga|intcomma}}</del>
                            &nbsp;
                            <strong>
                                Rp. {% with numerator=row.harga|mul:row.diskon|div:100%}
                                {{row.harga|sub:numerator|floatformat|intcomma}}
                                {% endwith %}
                            </strong>
                            {%else%}
                            <strong>
                                Rp. {{row.harga|intcomma}}
                            </strong>
                            {% endif %}
                        </div>

                        <div class="post-prev-more align-center">
                            <a href="{% url 'produk:show' row.slug %}" class="btn btn-mod btn-gray btn-round"><i
                                    class="fa fa-eye"></i> Lihat
                                Detail</a>
                        </div>

                    </div>
                    {% endfor %}

                </div>
                {% if produk.paginator.num_pages > 1 %}
                {% include 'layout/_pagination.html' with items=produk %}
                {% endif %}
            </div>
            <div class="col-sm-4 col-md-3 col-md-offset-1 sidebar">
                <div class="widget">
                    <h5 class="widget-title font-alt">Kategori</h5>
                    <div class="widget-body">
                        <ul class="clearlist widget-menu">
                            {% for row in kategori %}
                            <li>
                                <a href="{% url 'produk:kategori' row.slug %}" title="">{{row.nama}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
{% endblock content %}

produk/templates/produk/kategori.html
{% extends 'layout/base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">

        <div class="row">

            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Produk</h1>
                <div class="hs-line-4 font-alt">
                    Kategori : {{detailkategori.nama}}
                </div>
            </div>
        </div>

    </div>
</section>
<section class="page-section">
    <div class="container relative">

        <div class="row">
            <div class="col-sm-8">

                <div class="row multi-columns-row">
                    {% for row in produk %}
                    <div class="col-md-4 col-lg-4 mb-60 mb-xs-40">

                        <div class="post-prev-img">
                            {% if row.gambar %}
                            <img src="{{row.gambar.url}}" alt="" />
                            {% endif %}
                            {% if row.stok != 0 %}
                            {% if row.diskon != 0 %}
                            <div class="intro-label">
                                <span class="label label-danger bg-green">{{row.diskon}}%</span>
                            </div>
                            {% endif%}
                            {% else %}
                            <div class="intro-label">
                                <span class="label label-danger bg-red">Habis</span>
                            </div>
                            {% endif %}

                        </div>

                        <div class="post-prev-title font-alt align-center">
                            <a href="{% url 'produk:show' row.slug %}">{{row.nama}}</a>
                        </div>

                        <div class="post-prev-text align-center">
                            Stok : {{row.stok}} Pcs <br>
                            {% if row.diskon != 0 %}
                            <del>Rp. {{row.harga|intcomma}}</del>
                            &nbsp;
                            <strong>
                                {% with numerator=row.harga|mul:row.diskon|div:100%}
                                    {{row.harga|sub:numerator|floatformat|intcomma}}
                                {% endwith %}
                            </strong>
                            {%else%}
                            <strong>
                                Rp. {{row.harga|intcomma}}
                            </strong>
                            {% endif %}
                        </div>

                        <div class="post-prev-more align-center">
                            <a href="{% url 'produk:show' row.slug %}" class="btn btn-mod btn-gray btn-round"><i class="fa fa-eye"></i> Lihat
                                Detail</a>
                        </div>

                    </div>
                    {% endfor %}

                </div>

                <!-- Pagination -->
                {% if produk.paginator.num_pages > 1 %}
                <!-- start -->
                {% include 'layout/_pagination.html' with items=produk %}
                <!-- end -->

                {% endif %}
            </div>
            <div class="col-sm-4 col-md-3 col-md-offset-1 sidebar">
                <div class="widget">
                    <h5 class="widget-title font-alt">Kategori</h5>
                    <div class="widget-body">
                        <ul class="clearlist widget-menu">
                            <li>
                                <a href="{% url 'produk:index' %}" title="">Semua Produk</a>
                            </li>
                            {% for row in kategori %}
                            <li>
                                <a href="{% url 'produk:kategori' row.slug %}" title="">{{row.nama}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
{% endblock content %}

produk/templates/produk/link_download.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
<form action="downloadfile/" method="POST">
    {% csrf_token %}
        <button type="submit">Download File</button>
</form>
    {{ block.super }}
{% endblock %}

produk/templates/produk/show.html
{% extends 'layout/base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Detail Produk</h1>
            </div>
        </div>
    </div>
</section>
<section class="page-section">
    <div class="container relative">
        <div class="row mb-60 mb-xs-30">
            <div class="col-md-4 mb-md-30">
                <div class="post-prev-img">
                    {% if barang.gambar %}
                    <a href="{{barang.gambar.url}}" class="lightbox-gallery-3 mfp-image"><img
                        src="{{barang.gambar.url}}" alt="" /></a>
                    {% endif %}
                   {% if barang.diskon != 0 %}
                    <div class="intro-label">
                        <span class="label label-danger bg-red">{{barang.diskon}}%</span>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-sm-8 col-md-5 mb-xs-40">
                {% if messages %}
                {% for message in messages %}
                <div class="alert {{ message.tags }}"><i class="fa fa-lg fa-check-circle-o"></i> {{ message }}</div>
                {% endfor %}
            <br>
            {% endif %}
                <h3 class="mt-0" style="text-transform: capitalize;">{{barang.nama}}</h3>
                <hr class="mt-0 mb-30" />
                <div class="row">
                    {% if barang.diskon != 0 %}
                    <div class="col-xs-6 lead mt-0 mb-20">
                        <del class="section-text">Rp. {{barang.harga|intcomma}}</del>
                        <strong>
                            Rp. {% with numerator=barang.harga|mul:barang.diskon|div:100%}
                            {{barang.harga|sub:numerator|floatformat|intcomma}}
                            {% endwith %}
                        </strong>
                    </div>
                    {% else %}
                    <div class="col-xs-6 lead mt-0 mb-20">
                        <strong>Rp. {{barang.harga|intcomma}}</strong>
                    </div>
                    {% endif %}
                </div>

                <hr class="mt-0 mb-30" />
                <div class="section-text mb-30">
                    {{barang.deskripsi}}
                </div>
                <hr class="mt-0 mb-30" />
                
                <div class="section-text small">
                    <div>Stok : {{barang.stok}} Pcs</div>
                    <div>Berat : {{barang.berat|div:1000}} Kg</div>
                    <div>Kategori : {{barang.kategori}}</div>
                    <div>Tanggal Posting : {{barang.tanggal_buat}}</div>
                    {% for row in contact %}
                    <div>Bingung Cara Order ? Hubungi : <br><a href="https://wa.me/{{row.nomer_hp_satu}}" target="blank()"> {{row.nomer_hp_satu}} (Admin 1)</a><br> <a href="https://wa.me/{{row.nomer_hp_dua}}" target="blank()"> {{row.nomer_hp_dua}} (Admin 2)</a></div>
                    {% endfor %}
                </div>
                <br>
                <hr class="mt-0 mb-30" />
                {% if user.is_authenticated %}
                <h3 class="mt-0">Masukan Keranjang</h3>
                <form action="{% url 'produk:show' barang.slug %}" class="form-group text-center" method="POST" onsubmit="return validasiform()">
                    <input type="hidden" id="stok" name="stok" value="{{barang.stok}}">
                    <input type="hidden" id="user" name="user" value="{{user.id}}">
                    <input type="hidden" id="barang" name="barang" value="{{barang.id}}">
                    <div id="errormsg" class="alert error hide">
                        <span id="errorisi"></span>
                    </div>
                    <div class="section-text mb-30">
                        {% csrf_token %}
                        {{form}}
                    </div>
                    <button type="button" onclick="history.go(-1)" class="btn btn-mod btn-circle btn-medium">Kembali</button> 
                    <button type="submit" class="btn btn-mod btn-circle btn-medium">Masukan Keranjang</button> 
                </form>
                {% else %}
                <div class="alert notice">Maaf, Anda harus <a href="{%url 'users:login' %}">Login</a>, untuk melakukan transaksi, atau <a href="{%url 'users:register' %}">Register</a> apabila belum memiliki akun
                            </div>
                <button type="button" onclick="history.go(-1)" class="btn btn-mod btn-circle btn-medium">Kembali</button> 
                {% endif %}
                </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block customjs %}
<script>
function validasiform() {
         if($('#jumlah').val()==0 || $('#jumlah').val()=='' ){
            $('#errorisi').html('Oops, Jumlah tidak boleh berjumlah kosong');
            $("#errormsg").removeClass("hide");
            return false;
        }else{
            if(parseInt($('#jumlah').val())>parseInt($('#stok').val())){
                $('#errorisi').html('Oops, Stok tidak cukup');
                $("#errormsg").removeClass("hide");
                return false;
            }else{
                $('#errorisi').html('');
                $("#errormsg").addClass("hide");
                return true;
            }
         }
  }
</script>
{% endblock customjs %}