blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('kategori/<int:kategori>',views.bykategori,name='kategori'),
    path('<slug:blogslug>',views.show,name='show'),
    path('',views.index,name='index'),
]

lancarjaya/urls.py
from django.contrib import admin
from django.conf import settings	
from django.urls import path , include
from django.conf.urls.static import static
from . import views
admin.site.site_header = "Lancar Jaya Shop"
admin.site.site_title = "LJS"
admin.site.index_title = "Lancar Jaya Shop Admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('produk/',include('produk.urls')),
    path('galeri/',include('galeri.urls')),
    path('testimoni/',include('testimoni.urls')),
    path('kontak/',include('contact.urls')),
    path('cara_belanja/',views.cara_belanja,name='cara_belanja'),
    path('cara_verifikasi/',views.cara_verifikasi,name='cara_verifikasi'),
    path('user/',include('users.urls')),
    path('pencarian/',views.pencarian,name='pencarian'),
    path('keranjang/',include('transaksi.urls')),
    path('',views.index,name='index'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name='users'

urlpatterns = [
    path('register',views.register,name='register'),
    path('editprofile',views.editprofile,name='editprofile'),
    path('alamat',views.tambahalamat,name='tambah-alamat'),
    path('alamat/edit',views.editalamat,name='edit-alamat'),
    path('login',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from alamat.models import pengguna

class Userregisterform(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-md input-md form-control', 'placeholder': 'Username'}))
    first_name = forms.CharField(label='Nama Depan',widget=forms.TextInput(attrs={'class': 'input-md form-control', 'placeholder': 'First Name'}), max_length=32)
    last_name=forms.CharField(label='Nama Belakang',widget=forms.TextInput(attrs={'class': 'input-md form-control', 'placeholder': 'Last Name'}), max_length=32)
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input-md form-control', 'placeholder': 'Email'}), max_length=64)
    password1=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class': 'input-md form-control', 'placeholder': 'Password'}))
    password2=forms.CharField(label='Konfirmasi Password',widget=forms.PasswordInput(attrs={'class': 'input-md form-control', 'placeholder': 'Password Again'}))


    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class Userchangedform(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-md input-md form-control', 'placeholder': 'Username'}))
    first_name = forms.CharField(label='Nama Depan',widget=forms.TextInput(attrs={'class': 'input-md form-control', 'placeholder': 'First Name'}), max_length=32)
    last_name=forms.CharField(label='Nama Belakang',widget=forms.TextInput(attrs={'class': 'input-md form-control', 'placeholder': 'Last Name'}), max_length=32)
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input-md form-control', 'placeholder': 'Email'}), max_length=64)
    

    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)

class alamatuser(forms.Form):
    label = forms.CharField(widget=forms.TextInput(attrs={'class':'input-md input-md form-control','placeholder':'Label Alamat'}))
    CHOICES = (('Option 1', 'Option 1'),('Option 2', 'Option 2'),)
    kota = forms.ChoiceField(choices=CHOICES,widget=forms.Select(attrs={'class':'input-md input-md form-control','placeholder':'Label Alamat'}))
    Alamat_lengkap = forms.CharField(widget=forms.Textarea(attrs={'class':'input-md input-md form-control','placeholder':'Label Alamat'}))
            

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.forms import UserChangeForm
from .forms import Userregisterform, Userchangedform, alamatuser
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from alamat.models import pengguna
import http.client
import json

def register(request):
    if request.method == 'POST':
        form = Userregisterform(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Berhasil Membuat akun')
            return redirect('users:register')
    else:
        form = Userregisterform()
    context = {
        'head':'Register User',
        'form':form,
    }
    return render(request,'users/register.html',context)

@login_required
def tambahalamat(request):
    conn = http.client.HTTPSConnection("api.rajaongkir.com")
    
    if request.method == 'POST':
        newkota = request.POST['kota'].split('-')
        pengguna.objects.create(
            pengguna = User.objects.get(id=request.POST['kode']),
            label = request.POST['labelalamat'],
            alamat_lengkap = request.POST['alamat'],
            kota = newkota[1],
            kode_kota = newkota[0], 
        )
        messages.success(request, 'Berhasil Menambah Alamat')
        return redirect('users:editprofile')
    
    headers = { 'key': "5c9d1c918e391d9fee83d59759943b59" }
    conn.request("GET", "/starter/city", headers=headers)
    res = conn.getresponse()
    data = res.read()
    b = json.loads(data)
    form = alamatuser()
    context = {
        'form':form,
        'kota':b,
    }
    return render(request,'users/create_alamat.html',context)

@login_required
def editprofile(request):
    if request.method == 'POST':
        form = Userchangedform(request.POST,instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Berhasil Memperbarui akun')
            return redirect('users:editprofile')
    else:
        form = Userchangedform(instance=request.user)
    
    data_alamat = '';
    jumlah_alamat = pengguna.objects.filter(pengguna=User.objects.get(id=request.user.id)).count()
    if jumlah_alamat > 0 :
        data_alamat = pengguna.objects.get(pengguna=User.objects.get(id=request.user.id))
    
    context = {
        'alamat':data_alamat,
        'form':form,
        'jumlah_alamat':jumlah_alamat,
    }
    return render(request,'users/profile.html',context)

@login_required
def editalamat(request):
    conn = http.client.HTTPSConnection("api.rajaongkir.com")
    
    if request.method == 'POST':
        newkota = request.POST['kota'].split('-')
        t = pengguna.objects.get(id=request.POST['kode'])
        t.label = request.POST['labelalamat'] 
        t.alamat_lengkap = request.POST['alamat']
        t.kota = newkota[1]
        t.kode_kota = newkota[0]
        t.save()
        messages.success(request, 'Berhasil Memperbarui Alamat')
        return redirect('users:editprofile')

    headers = { 'key': "5c9d1c918e391d9fee83d59759943b59" }
    conn.request("GET", "/starter/city", headers=headers)
    res = conn.getresponse()
    data = res.read()
    b = json.loads(data)
    form = alamatuser()
    
    data_alamat = pengguna.objects.get(pengguna=User.objects.get(id=request.user.id))
    context = {
        'form':form,
        'kota':b,
        'alamat':data_alamat,
    }
    return render(request,'users/edit_alamat.html',context)    

users/templates/users/create_alamat.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Alamat</h1>
                <div class="hs-line-4 font-alt white">
                    Alamat dapat lebih dari satu, dan digunakan saat transaksi
                </div>
            </div>
        </div>
    </div>
</section>
<section class="page-section" id="contact">
    <div class="container relative">
        <h2 class="section-title font-alt mb-70 mb-sm-40">
            Tambah Alamat Anda
        </h2>
        <div class="row">
            {% if messages %}
            <div class="col-md-8 col-md-offset-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }}"><i class="fa fa-lg fa-check-circle-o"></i>{{message}}</div>
                {% endfor %}
            </div>
            {% endif %}
            <div class="col-md-8 col-md-offset-2">
                <form method="POST" class="form" action="{% url 'users:tambah-alamat'%}">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <div class="mb-20 mb-md-10">
                            <label for="">Label Alamat</label>
                            <input type="text" name="labelalamat" id="labelalamat" class="input-md form-control" required>
                            <input type="hidden" name="kode" value="{{user.id}}">
                        </div>
                        <div class="mb-20 mb-md-10">
                            <label for="">Kota/Kabupaten</label>
                            <select class="input-md form-control" id="kota" name="kota" placeholder="Placeholder">
                                <option selected disabled hidden>Pilih Kota</option>
                                {% for objCity in kota.rajaongkir.results %}
                                <option value="{{objCity.city_id}}-{{objCity.type}} {{objCity.city_name}}">
                                    {{objCity.type}} {{objCity.city_name}}</option>
                                {% endfor%}
                            </select>
                        </div>
                        <div class="mb-20 mb-md-10">
                            <label for="">Alamat Lengkap</label>
                            <textarea name="alamat" class="input-md form-control"></textarea>
                        </div>
                    </fieldset>
                    <div class="form-group">
                        <button type="submit" class="submit_btn btn btn-mod btn-medium btn-round">Simpan</button>
                        <button type="reset" onclick="history.go(-1)"
                            class="submit_btn btn btn-mod btn-medium btn-round">Kembali</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

users/templates/users/edit_alamat.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Alamat</h1>
                <div class="hs-line-4 font-alt white">
                    Anda tidak dapat berbelanja sebelum menambahkan alamat
                </div>
            </div>
        </div>
    </div>
</section>
<section class="page-section" id="contact">
    <div class="container relative">
        <h2 class="section-title font-alt mb-70 mb-sm-40">
            Edit Alamat Anda
        </h2>
        <div class="row">
            {% if messages %}
            <div class="col-md-8 col-md-offset-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }}"><i class="fa fa-lg fa-check-circle-o"></i>{{message}}</div>
                {% endfor %}
            </div>
            {% endif %}
            <div class="col-md-8 col-md-offset-2">
                <form method="POST" class="form" action="{% url 'users:edit-alamat'%}">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <div class="mb-20 mb-md-10">
                            <label for="">Label Alamat</label>
                            <input type="text" name="labelalamat" value="{{alamat.label}}" id="labelalamat" class="input-md form-control" required>
                            <input type="hidden" name="kode" value="{{alamat.id}}">
                        </div>
                        <div class="mb-20 mb-md-10">
                            <label for="">Kota/Kabupaten</label>
                            <select class="input-md form-control" id="kota" name="kota" placeholder="Placeholder">
                                {% for objCity in kota.rajaongkir.results %}
                                <option value="{{objCity.city_id}}-{{objCity.type}} {{objCity.city_name}}" {% if objCity.city_id == alamat.kode_kota %} selected {% endif %}>
                                    {{objCity.type}} {{objCity.city_name}}</option>
                                {% endfor%}
                            </select>
                        </div>
                        <div class="mb-20 mb-md-10">
                            <label for="">Alamat Lengkap</label>
                            <textarea name="alamat" class="input-md form-control">{{alamat.alamat_lengkap}}</textarea>
                        </div>
                    </fieldset>
                    <div class="form-group">
                        <button type="submit" class="submit_btn btn btn-mod btn-medium btn-round">Simpan</button>
                        <button type="reset" onclick="history.go(-1)"
                            class="submit_btn btn btn-mod btn-medium btn-round">Kembali</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

users/templates/users/login.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">
        
        <div class="row">
            
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Login</h1>
                <div class="hs-line-4 font-alt">
                    Login & rasakan kemudahan berbelanja online di Lancar Jaya
                </div>
            </div>
            
            <div class="col-md-4 mt-30">
            </div>
        </div>
        
    </div>
</section>
<!-- End Head Section -->


<!-- Section -->
<section class="page-section">
    <div class="container relative">
        <div class="tab-content tpl-minimal-tabs-cont section-text">
            
            <div class="tab-pane fade in active" id="mini-one">
                                      
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        
                        <form class="form contact-form" id="contact_form" method="POST">
                            {% csrf_token %}
                            {{form|crispy}}
                            
                            <div class="clearfix">
                                
                                <div class="cf-left-col">
                                                                         
                                    <div class="form-tip pt-20">
                                        <a href="{% url 'users:register' %}">Daftar Menjadi Anggota</a>
                                    </div>
                                    
                                </div>
                                
                                <div class="cf-right-col">
                                    
                                    <!-- Send Button -->
                                    <div class="align-right pt-10">
                                        <button type="submit" class="submit_btn btn btn-mod btn-medium btn-round" id="login-btn">Login</button>
                                    </div>
                                    
                                </div>
                                
                            </div>
                            
                        </form>
                        
                    </div>
                </div>
                
            </div>
            
        </div>
        
    </div>
</section>
{% endblock content %}

users/templates/users/logout.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">
        
        <div class="row">
            
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Logout</h1>
            </div>
            
            <div class="col-md-4 mt-30">
            </div>
        </div>
        
    </div>
</section>
<!-- End Head Section -->


<!-- Section -->z
<section class="page-section">
    <div class="container relative">
        <div class="tab-content tpl-minimal-tabs-cont section-text">
            
            <div class="tab-pane fade in active" id="mini-one">
                                      
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 text-center">
                        <h1 class="display-4">Hai !</h1>
                            <p class="lead">Anda telah logout, Sampai jumpa lagi</p>
                            <a class="submit_btn btn btn-mod btn-medium btn-round" href="{% url 'index' %}" role="button">Home</a>
                            <a class="submit_btn btn btn-mod btn-medium btn-round" href="{% url 'users:login' %}" role="button">Login lagi</a>
                    </div>
                </div>
                
            </div>
            
        </div>
        
    </div>
</section>
{% endblock content %}

users/templates/users/profile.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Edit Profile</h1>
                <div class="hs-line-4 font-alt white">
                    Perbarui Data Anda
                </div>
            </div>
        </div>
    </div>
</section>
<section class="page-section" id="contact">
    <div class="container relative">
        <h2 class="section-title font-alt mb-70 mb-sm-40">
            Edit Profil Anda
        </h2>
        <div class="row">
            {% if messages %}
            <div class="col-md-8 col-md-offset-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }}"><i class="fa fa-lg fa-check-circle-o"></i>{{message}}</div>
                {% endfor %}
            </div>
            {% endif %}
            <div class="col-md-8 col-md-offset-2">
                <form method="POST" class="form">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{form}}
                    </fieldset>
                    <div class="form-group">
                        <button type="submit" class="submit_btn btn btn-mod btn-medium btn-round">Simpan</button>
                        <button type="button" onclick="history.go(-1)"
                            class="submit_btn btn btn-mod btn-medium btn-round">Kembali</button>
                    </div>
                    {% if jumlah_alamat == 0 %}
                    Tambahkan <a href="{% url 'users:tambah-alamat' %}">alamat</a> pengiriman
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    <hr>
    {% if jumlah_alamat > 0 %}
    <div class="benefits-grid">
        <div class="benefit-item">
            <div class="benefit-icon">
                <i class="fa fa-paper-plane-o"></i>
            </div>
            <h3 class="benefit-title font-alt">Alamat {{alamat.label}}</h3>
            <p>{{alamat.kota}}</p>
            <div class="benefits-descr">
                {{alamat.alamat_lengkap}}
            </div>
        </div>
        <br>
        <a href="{% url 'users:edit-alamat' %}" class="btn btn-mod btn-medium btn-round">Edit Alamat</a>
    </div>
    {% endif %}
</section>
{% endblock content %}

users/templates/users/register.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">

        <div class="row">

            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Register</h1>
                <div class="hs-line-4 font-alt white">
                    Buat akun dan belanja sekarang juga
                </div>
            </div>

        </div>

    </div>
</section>
<section class="page-section" id="contact">
    <div class="container relative">

        <h2 class="section-title font-alt mb-70 mb-sm-40">
            Daftar Menjadi Anggota
        </h2>

        <!-- Contact Form -->

        <div class="row">
            {% if messages %}
            <div class="col-md-8 col-md-offset-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }}"><i class="fa fa-lg fa-check-circle-o"></i> {{ message }}</div>
                {% endfor %}
            </div>
            {% endif %}
            <div class="col-md-8 col-md-offset-2">
                <form method="POST" class="form">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{form}}
                    </fieldset>
                    <div class="form-group">
                        <button type="submit" class="submit_btn btn btn-mod btn-medium btn-round">Daftar</button>
                        <button type="button" onclick="history.go(-1)" class="submit_btn btn btn-mod btn-medium btn-round">Kembali</button>
                    </div>
                </form>
                Punya akun ? <a href="{% url 'users:login' %}">login</a> sekarang
            </div>
        </div>
    </div>
</section>
{% endblock content %}