blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('kategori/<int:kategori>',views.bykategori,name='kategori'),
    path('<slug:blogslug>',views.show,name='show'),
    path('',views.index,name='index'),
]

galeri/urls.py
from django.urls import path
from . import views

app_name='galeri'

urlpatterns = [
	path('kategori/<int:kategori>',views.index,name='kategori'),
	path('',views.index,name='index'),
]

lancarjaya/urls.py
from django.contrib import admin
from django.conf import settings	
from django.urls import path , include
from django.conf.urls.static import static
from . import views
admin.site.site_header = "Lancar Jaya Shop"
admin.site.site_title = "LJS"
admin.site.index_title = "Lancar Jaya Shop Admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('produk/',include('produk.urls')),
    path('galeri/',include('galeri.urls')),
    path('testimoni/',include('testimoni.urls')),
    path('kontak/',include('contact.urls')),
    path('cara_belanja/',views.cara_belanja,name='cara_belanja'),
    path('cara_verifikasi/',views.cara_verifikasi,name='cara_verifikasi'),
    path('user/',include('users.urls')),
    path('pencarian/',views.pencarian,name='pencarian'),
    path('keranjang/',include('transaksi.urls')),
    path('',views.index,name='index'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produk/urls.py
from django.urls import path
from . import views
app_name = 'produk'

urlpatterns=[
    path('',views.index,name='index'),
    path('<slug:slugbarang>',views.show,name='show'),
    path('kategori/<slug:slugkategori>',views.kategori,name='kategori')
]

templates/cara_belanja.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">
        
        <div class="row">
            
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Cara Belanja</h1>
                <div class="hs-line-4 font-alt white">
                    Selamat Membaca petunjuk pembelian produk Kami
                </div>
            </div>
            
        </div>
        
    </div>
</section>
<!-- End Head Section -->

<!-- Section -->
<!-- <section class="page-section"> -->
    <div class="container relative">
        
        <div class="row">
            
            <!-- Content -->
            <div class="col-sm-12">
                
                <!-- Post -->
                <div class="blog-item mb-80 mb-xs-40">
                    
                    <!-- Text -->
                    <div class="blog-item-body">
                        
                        <!-- Media Gallery -->
                        <div class="blog-media mt-40 mb-40 mb-xs-30" style="text-align: center;">
                            <ul class="clearlist content-slider">
                                <li>
                                    <img src="{% static 'assets/images/shopper.png' %}" alt="" style="max-width: 550px;">
                                </li>
                            </ul>
                        </div>

                        <div>
                        	<ol>
                        		<li>Pastikan telah menjadi member / telah memiliki akun sebagai customer Lancar Jaya Shop</li>
                        		<li>Lengkapi alamat anda untuk pengiriman barang yang akan di beli</li>
                        		<li>Pilih barang yang akan anda beli, kemudian masukan ke keranjang</li>
                        		<li>Check out barang / lakukan transaksi</li>
                        		<li>Happy Shopping gengs</li>
                        	</ol>
                    	</div>
                    </div>
                    <!-- End Text -->
                    
                </div>
                <!-- End Post -->

            </div>
            <!-- End Content -->
            
        </div>
        
    </div>
<!-- </section> -->
<!-- End Section -->

{% endblock content %}

templates/cara_verifikasi.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">
        
        <div class="row">
            
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Cara Verifikasi</h1>
                <div class="hs-line-4 font-alt white">
                    Selamat Membaca petunjuk verifikasi pembelian produk Kami
                </div>
            </div>
            
        </div>
        
    </div>
</section>
<!-- End Head Section -->

<!-- Section -->
<!-- <section class="page-section"> -->
    <div class="container relative">
        
        <div class="row">
            
            <!-- Content -->
            <div class="col-sm-12">
                
                <!-- Post -->
                <div class="blog-item mb-80 mb-xs-40">
                    
                    <!-- Text -->
                    <div class="blog-item-body">
                        
                        <!-- Media Gallery -->
                        <div class="blog-media mt-40 mb-40 mb-xs-30" style="text-align: center;">
                            <ul class="clearlist content-slider">
                                <li>
                                    <img src="{% static 'assets/images/verifikasi_image.png' %}" alt="" style="max-width: 550px;">
                                </li>
                            </ul>
                        </div>

                        <div>
                        	<ol>
                        		<li>Transfer dana yang sesuai dengan total biaya produk yang tertera ke nomer rekening berikut ini <b>928837817167755-BRI</b> </li>
                        		<li>Setelah selesai melakukan transfer dana, silahkan hubungi nomer WA salah satu Admin kami untuk melakukan konfirmasi pembayaran produk, berikut ini <b> Admin 1 : <a href="https://wa.me/085607039487" target="blank()">085607039487</a> </b> dan <b> Admin 2 : <a href="https://wa.me/081984758997" target="blank()">081984758997</a> </b></li>
                        		<li>Setelah konfirmasi pembayaran ke Admin, silahkan tunggu beberapa saat untuk persetujuan dari admin</li>
                        		<li>Jika pembayaran sudah konfirmasi Admin, silahkan cek kembali <b>Pesanan Saya </b> untuk mengecek Resi Pengiriman dari produk Anda</li>
                        		<li>Tunggu sampai produk Anda terkirim dan Silahkan berbelanja di toko kami lagi</li>
                                <li>Happy Shopping Gengs and Thank You So Much :)</li>
                        	</ol>
                    	</div>
                    </div>
                    <!-- End Text -->
                    
                </div>
                <!-- End Post -->
                <!-- tombol kembali -->
                <div class="col-sm-12" style="text-align: center;">
                    <button type="submit" class="btn btn-mod btn-round btn-gray btn-small mb-xs-10" onclick="history.go(-1)">Kembali</button>
                </div>

            </div>
            <!-- End Content -->
            
        </div>
        
    </div>
<!-- </section> -->
<!-- End Section -->

{% endblock content %}

templates/index.html
{% extends 'layout/base.html' %}

{% load humanize %}
{% load mathfilters %}
{% load static %}
{% block content %}
<div class="home-section fullwidth-slider bg-dark" id="home">
    {% for row in slider %}
    <section class="home-section bg-scroll bg-dark-alfa-30" data-background="{{row.gambar.url}}">
        <div class="js-height-full container">
            <div class="home-content">
                <div class="home-text">
                    <h2 class="hs-line-14 font-alt mb-50 mb-xs-30">
                        {{row.head}}
                    </h2>
                    <p>{{row.deskripsi}}</p>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}
    
</div>

<!-- start produk terbaru -->
<section class="page-section">
    <div class="container relative">
        <h2 class="section-title font-alt align-left mb-70 mb-sm-40">
            Produk Terbaru
            <a href="{% url 'produk:index' %}" class="section-more right">Lihat Semua Produk <i class="fa fa-angle-right"></i></a>
        </h2>
        <div class="row multi-columns-row">
            {% for row in produk %}
            <div class="col-md-3 col-lg-3 mb-60 mb-xs-40 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                <div class="post-prev-img">
                    {% if row.gambar %}
                    <img src="{{row.gambar.url}}" alt="" />
                    {% endif %}
                    {% if row.stok != 0 %}
                        {% if row.diskon != 0 %}
                        <div class="intro-label">
                            <span class="label label-danger bg-green">{{row.diskon}}%</span>
                        </div>
                        {% endif%}
                    {% else %}
                        <div class="intro-label">
                            <span class="label label-danger bg-red">Habis</span>
                        </div>
                    {% endif %}
                    
                </div>
                <div class="post-prev-title font-alt align-center">
                    <a href="{% url 'produk:show' row.slug %}">{{row.nama}}</a>
                </div>
                <div class="post-prev-text align-center">
                    Stok : {{row.stok}} Pcs <br>
                    {% if row.diskon != 0 %}
                    <del>Rp. {{row.harga|intcomma}}</del>
                    &nbsp;
                    <strong>
                        {% with numerator=row.harga|mul:row.diskon|div:100%}
                        {{row.harga|sub:numerator|floatformat|intcomma}}
                        {% endwith %}
                    </strong>
                    {%else%}
                    <strong>
                        Rp. {{row.harga|intcomma}}
                    </strong>
                    {% endif %}
                </div>
                <div class="post-prev-more align-center">
                    <a href="{% url 'produk:show' row.slug %}" class="btn btn-mod btn-gray btn-round"><i
                            class="fa fa-eye"></i> Lihat
                        Detail</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- end produk -->

<!-- galeri -->
<section class="page-section bg-dark">
    <div class="container relative">

        <h2 class="section-title font-alt align-left mb-70 mb-sm-40">
            Galeri Terbaru
            <a href="{% url 'galeri:index' %}" class="section-more right">Lihat Semua Galeri<i
                    class="fa fa-angle-right"></i></a>
        </h2>

        <ul class="works-grid work-grid-3 work-grid-gut clearfix font-alt hover-white hide-titles" id="work-grid">
            {% for row in galeri_home %}
            <li class="work-item mix {{row.kategori.slug}}">
                <a href="{{row.gambar.url}}" class="work-lightbox-link mfp-image">

                    <div class="work-img">
                        <img src="{{row.gambar.url}}" alt="Work" />
                    </div>

                    <div class="work-intro">

                        <h3 class="work-title">{{row.kategori.nama}}</h3>

                        <div class="work-descr">
                            {{row.deskripsi}}
                        </div>
                        
                    </div>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
<!-- end galeri -->

<!-- artikel -->
<section class="page-section" id="news">
    <div class="container relative">

        <h2 class="section-title font-alt align-left mb-70 mb-sm-40">
            Artikel Terbaru

            <a href="{% url 'blog:index' %}" class="section-more right">Lihat Semua Artikel<i
                    class="fa fa-angle-right"></i></a>

        </h2>

        <div class="row multi-columns-row">

            <!-- Post Item -->
            {% for row in artikel %}
            <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                {% if row.gambar %}
                <div class="post-prev-img">
                    <a href="{% url 'blog:show' row.slug %}"><img src="{{row.gambar.url}}" alt="" /></a>
                </div>
                {% endif %}
                <div class="post-prev-title font-alt">
                    {{row.judul}}
                </div>

                <div class="post-prev-info font-alt">
                    {{row.kategori}} || {{row.tanggal}}
                </div>

                <div class="post-prev-text">
                    {{row.isi|slice:"0:130"}}
                </div>

                <div class="post-prev-more">
                    <a href="{% url 'blog:show' row.slug %}" class="btn btn-mod btn-gray btn-round">Lanjut Baca <i class="fa fa-angle-right"></i></a>
                </div>

            </div>
            {% endfor %}
            <!-- End Post Item -->
        </div>
    </div>
</section>
<!-- end artikel -->

<!-- start tesimoni -->
<section class="page-section bg-dark fullwidth-slider bg-scroll">
    {% for row in testi %}
    <div>
        <div class="container relative">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 align-center">
                    <!-- Section Icon -->
                    <div class="section-icon">
                        <span class="icon-quote"></span>
                    </div>
                    <!-- Section Title -->
                    <h3 class="small-title font-alt">Testimoni</h3>
                    <blockquote class="testimonial">
                        <p>
                            {{row.perihal}} - {{row.deskripsi}}
                        </p>
                        <footer class="testimonial-author">
                            {{row.nama}} - {{row.email}}
                        </footer>
                    </blockquote>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</section>
<!-- end testimoni -->

{% endblock content %}

templates/pencarian.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<section class="page-section bg-dark parallax-3">
    <div class="relative container align-left">

        <div class="row">

            <div class="col-md-12">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0"></h1>
                <br>
                <div class="hs-line-4 font-alt white" align="center">
                    Hasil Pencarian
                </div>
            </div>
            
        </div>
        
    </div>
</section>

<section class="page-section">
    {% if hasil %}
    <div class="container relative">

        <div class="row">

            <!-- Content -->
            <div class="col-sm-12">

                <div class="row multi-columns-row">

                    <!-- Post Item -->
                    {% for row in hasil %}
                    <div class="col-md-4 col-lg-4 mb-60 mb-xs-40">

                        <div class="post-prev-img">
                            <img src="{{row.gambar.url}}" alt=""/>
                        </div>
                        
                        <div class="post-prev-title font-alt">
                            {{row.nama}}
                        </div>
                        <div class="post-prev-info font-alt">
                            {{row.kategori}} || {{row.tanggal_buat}}
                        </div>
                        <div class="post-prev-text">
                            {{row.deskripsi|slice:"0:149"}}
                        </div>
                        <br>
                        <div class="post-prev-more align-center">
                            <a href="{% url 'produk:show' row.slug %}" class="btn btn-mod btn-gray btn-round"><i class="fa fa-eye"></i> Lihat
                                Detail</a>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- End Post Item -->
                    
                </div> 
            </div>
        </div>
        
    </div>
    {% else %}
    <div class="container relative">

        <div class="row">

            <!-- Content -->
            <div class="col-sm-12">

                <div class="row multi-columns-row">

                    <!-- Post Item -->
                    <h3 align="center">"Ooops Produk Yang dicari Tidak Ada"</h3>
                    <!-- End Post Item -->
                    
                </div> 
            </div>
        </div>
        
    </div>
    {% endif %}
</section>

<section class="small-section bg-dark">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-12">
                <div class="hs-line-4 font-alt white" align="center">
                    Artikel
                </div>
            </div>
        </div>
    </div>
</section>
<section class="page-section">
    {% if hasil2 %}
    <div class="container relative">

        <div class="row">

            <!-- Content -->
            <div class="col-sm-12">

                <div class="row multi-columns-row">

                    <!-- Post Item -->
                    {% for row in hasil2 %}
                    <div class="col-md-4 col-lg-4 mb-60 mb-xs-40">

                        <div class="post-prev-img">
                            <img src="{{row.gambar.url}}" alt=""/>
                        </div>
                        
                        <div class="post-prev-title font-alt">
                            {{row.judul}}
                        </div>
                        <div class="post-prev-info font-alt">
                            {{row.kategori}} || {{row.tanggal}}
                        </div>
                        <div class="post-prev-text">
                            {{row.isi|slice:"0:149"}}
                        </div>
                        <br>
                        <div class="post-prev-more align-center">
                            <a href="{% url 'blog:show' row.slug %}" class="btn btn-mod btn-gray btn-round"><i class="fa fa-eye"></i> Lihat
                                Detail</a>
                        </div>
                                               
                    </div>
                    {% endfor %}
                    <!-- End Post Item -->
                    
                </div> 
            </div>
        </div>
        
    </div>
    {% else %}
    <div class="container relative">

        <div class="row">

            <!-- Content -->
            <div class="col-sm-12">

                <div class="row multi-columns-row">

                    <!-- Post Item -->
                    <h3 align="center">"Ooops Artikel Yang dicari Tidak Ada"</h3>
                    <!-- End Post Item -->
                    
                </div> 
            </div>
        </div>
        
    </div>
    {% endif %}
</section>

{% endblock content %}