blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('kategori/<int:kategori>',views.bykategori,name='kategori'),
    path('<slug:blogslug>',views.show,name='show'),
    path('',views.index,name='index'),
]

contact/urls.py
from django.urls import path
from . import views

app_name='contact'

urlpatterns = [
	path('',views.index,name='index'),
]

galeri/urls.py
from django.urls import path
from . import views

app_name='galeri'

urlpatterns = [
	path('kategori/<int:kategori>',views.index,name='kategori'),
	path('',views.index,name='index'),
]

lancarjaya/urls.py
from django.contrib import admin
from django.conf import settings	
from django.urls import path , include
from django.conf.urls.static import static
from . import views
admin.site.site_header = "Lancar Jaya Shop"
admin.site.site_title = "LJS"
admin.site.index_title = "Lancar Jaya Shop Admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('produk/',include('produk.urls')),
    path('galeri/',include('galeri.urls')),
    path('testimoni/',include('testimoni.urls')),
    path('kontak/',include('contact.urls')),
    path('cara_belanja/',views.cara_belanja,name='cara_belanja'),
    path('cara_verifikasi/',views.cara_verifikasi,name='cara_verifikasi'),
    path('user/',include('users.urls')),
    path('pencarian/',views.pencarian,name='pencarian'),
    path('keranjang/',include('transaksi.urls')),
    path('',views.index,name='index'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produk/urls.py
from django.urls import path
from . import views
app_name = 'produk'

urlpatterns=[
    path('',views.index,name='index'),
    path('<slug:slugbarang>',views.show,name='show'),
    path('kategori/<slug:slugkategori>',views.kategori,name='kategori')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name='users'

urlpatterns = [
    path('register',views.register,name='register'),
    path('editprofile',views.editprofile,name='editprofile'),
    path('alamat',views.tambahalamat,name='tambah-alamat'),
    path('alamat/edit',views.editalamat,name='edit-alamat'),
    path('login',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]

templates/layout/_pagination.html
<!-- Pagination -->
<div class="pagination">
    {% if items.has_previous %}

        <a href="?page=1">First</a>
        &nbsp;&nbsp;
        <a href="?page={{ items.previous_page_number }}">Previous</a>

        <!-- <i class="fa fa-angle-right"></i> -->
    {% endif %}
    &nbsp;&nbsp;
    {% if items.has_next %}
        <!-- <i class="fa fa-angle-left"></i> -->

        <a href="?page={{ items.next_page_number }}"> Next </a>
        &nbsp;&nbsp;
        <a href="?page={{ items.paginator.num_pages }}"> Last </a>
    {% endif %}
</div>

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>lancar jaya</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta charset="utf-8">
        <meta name="author" content="https://themeforest.net/user/bestlooker/portfolio">
        <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
        <!-- Favicons -->
        <link rel="shortcut icon" href="{% static 'assets/images/favicon-lancar-jaya.png' %}">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style-responsive.css'%}">
        <link rel="stylesheet" href="{% static 'assets/css/animate.min.css'%}">
        <link rel="stylesheet" href="{% static 'assets/css/vertical-rhythm.min.css'%}">
        <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css'%}">
        <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css'%}">
        {% block customcss %}
        {% endblock customcss %}        
        
    </head>
    <body class="appear-animate">
        
        <!-- Page Loader -->        
        <div class="page-loader">
            <div class="loader">Loading...</div>
        </div>
        <!-- End Page Loader -->
        
        <!-- Page Wrap -->
        <div class="page" id="top">
            
            <!-- Navigation panel -->
            {% include 'layout/nav.html' %}
            <!-- End Navigation panel -->
            
            
            {% block content %}
            
            {% endblock content %}
            
            
            <!-- Foter -->
            <footer class="page-section bg-gray-lighter footer pb-60">
                <div class="container">
                    <div class="footer-social-links mb-110 mb-xs-60">
                        <a href="#" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
                        <a href="#" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>
                        <a href="#" title="Behance" target="_blank"><i class="fa fa-behance"></i></a>
                        <a href="#" title="LinkedIn+" target="_blank"><i class="fa fa-linkedin"></i></a>
                        <a href="#" title="Pinterest" target="_blank"><i class="fa fa-pinterest"></i></a>
                    </div>
                    <!-- End Social Links -->  
                    
                    <!-- Footer Text -->
                    <div class="footer-text">
                        
                        <!-- Copyright -->
                        <div class="footer-copy font-alt">
                            <a href="{%url 'index' %}" target="_blank">&copy; Lancar Jaya 2020</a>.
                        </div>
                        <!-- End Copyright -->
                        
                        <div class="footer-made">
                            Made with love for great people.
                        </div>
                        
                    </div>
                    <!-- End Footer Text --> 
                    
                 </div>
                 
                 
                 <!-- Top Link -->
                 <div class="local-scroll">
                     <a href="#top" class="link-to-top"><i class="fa fa-caret-up"></i></a>
                 </div>
                </footer>        
        
        </div>
        <script type="text/javascript" src="{% static 'assets/js/jquery-1.11.2.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.easing.1.3.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js'%}"></script>        
        <script type="text/javascript" src="{% static 'assets/js/SmoothScroll.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.scrollTo.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.localScroll.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.viewport.mini.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.countTo.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.appear.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.sticky.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.parallax-1.1.3.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.fitvids.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/owl.carousel.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/isotope.pkgd.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/imagesloaded.pkgd.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.magnific-popup.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/wow.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/masonry.pkgd.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.simple-text-rotator.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.lazyload.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/all.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/contact-form.js'%}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.ajaxchimp.min.js'%}"></script> 
        {% block customjs %}
        {% endblock customjs %}       
        </body>
</html>

templates/layout/nav.html
{% load static %}
<nav class="main-nav dark transparent stick-fixed">
    <div class="full-wrapper relative clearfix">
        <div class="nav-logo-wrap local-scroll">
            <a href="{%url 'index' %}" class="logo">
                <img src="{% static 'assets/images/logo-white-lancar-jaya.png' %}" alt="" />
            </a>
        </div>
        <div class="mobile-nav">
            <i class="fa fa-bars"></i>
        </div>
        <div class="inner-nav desktop-nav">
            <ul class="clearlist">
                <li>
                    <a href="{%url 'index' %}" class="active">Home</a>
                </li>
                <li>
                    <a href="{%url 'produk:index' %}" class="active">Produk</a>
                </li>
                <li>
                    <a href="{%url 'galeri:index' %}" class="active">Galeri</a>
                </li>
                <li>
                    <a href="{%url 'blog:index' %}" class="active">Blog</a>
                </li>
                <li>
                    <a href="{%url 'testimoni:index' %}" class="active">Testimoni</a>
                </li>
                <li>
                    <a href="{%url 'contact:index' %}" class="active">Kontak</a>
                </li>
                <li><a>&nbsp;</a></li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'transaksi:keranjang' user.username %}"><i class="fa fa-shopping-cart"></i>
                        Keranjang</a>
                </li>
                <li>
                    <a href="#" class="mn-has-sub">{{user.username}} <i class="fa fa-angle-down"></i></a>
                    <ul class="mn-sub">
                        <li><a href="{%url 'users:editprofile' %}">Edit Profile</a></li>
                        <li><a href="{%url 'transaksi:pesanansaya' %}">Pesanan Saya</a></li>
                        <li><a href="{%url 'cara_belanja' %}">Cara Belanja</a></li>
                        <li><a href="{%url 'users:logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li>
                    <a href="{%url 'users:login' %}" class="active">Login</a>
                </li>
                <li>
                    <a href="{%url 'users:register' %}" class="active">Register</a>
                </li>
                {% endif %}
                <li>
                    <a class="mn-has-sub"><i class="fa fa-search"></i> Search</a>
                    <ul class="mn-sub">
                        <li>
                            <div class="mn-wrap">
                                <form action="{% url 'pencarian' %}" method="get" class="form">
                                    <div class="search-wrap">
                                        <input type="text" name="cari" class="form-control search-field"
                                            placeholder="Nama Produk / Artikel" required>
                                        <button class="search-button animate" type="submit" title="Start Search">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </li>

                    </ul>

                </li>

            </ul>
        </div>
    </div>
</nav>